---
ID: "e4deb43c-467a-472e-955b-20ea09c0b40c"
Parent: "52dc489f-d611-4893-b77c-fe286c7aeecf"
Template: "854ba861-63ea-4a0c-8c7b-541e9a7ec4c1"
Path: /sitecore/system/Settings/Rules/Marketing Workflows/Tags/Engagement Automation
DB: master
SharedFields:
- ID: "42f77151-098f-496a-94cf-590b7edeeabe"
  Hint: Tags
  Type: Multilist
  Value: "{096C7106-1681-45C6-B4CF-CF513A81EE18}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150318T120741Z
