---
ID: "ec3069a3-2452-4c1e-b946-328ceabeb822"
Parent: "e5e5393e-ac53-4777-bfe3-bb9e6a5d70e2"
Template: "e5e5393e-ac53-4777-bfe3-bb9e6a5d70e2"
Path: /sitecore/templates/BBC/News/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{DB321917-29E6-4497-9009-C5ED3B4DF5EF}">
        <r
          id="{6819D55D-612E-4761-83E4-AE63ED12A025}"
          ph="header"
          uid="{BFABD2DC-74BA-4239-81FC-F92FB73780BC}" />
        <r
          id="{52430B2E-E09A-4CF3-96B2-E10B28FC39E9}"
          ph="content"
          uid="{7CC05684-47D4-4567-BAD6-A848AB539892}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170106T024633Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
